DROP TABLE IF EXISTS brain_sessions CASCADE;
DROP TABLE IF EXISTS brain_errors CASCADE;
DROP TABLE IF EXISTS brain_relations CASCADE;
DROP TABLE IF EXISTS brain_observations CASCADE;
DROP TABLE IF EXISTS brain_entities CASCADE;
