//! Git-friendly export/import for cuba-memorys (v0.8).
//!
//! Layout written to `CUBA_SYNC_DIR` (default `./.cuba-memorys/`):
//!
//! ```text
//! .cuba-memorys/
//! ├── manifest.json                # schema_version, hash, project, exported_at
//! ├── projects.json
//! ├── entities/<slug>.json         # 1 file per entity (with observations[])
//! ├── episodes/<yyyy-mm>/<id>.json # partitioned monthly
//! ├── decisions/<id>.json
//! ├── errors/<id>.json
//! ├── relations.json               # single array (small)
//! └── embeddings.bin.zst           # opt-in via with_embeddings=true
//! ```
//!
//! Embeddings are omitted by default (1.5KB/obs base64 → ~30x diff bloat).
//! On import they are re-generated by ONNX (~10ms/obs).
//!
//! Import dedup uses primary-key UUIDs + `INSERT … ON CONFLICT DO NOTHING`,
//! which makes re-imports safe (idempotent). Tracking lives in
//! `brain_sync_state` (manifest_hash PK).

pub mod cas;
pub mod chunk;
pub mod compressor;
pub mod transport;
pub mod paths;

pub use chunk::Manifest;
